[project]
name = "streamlit-groq-chatbot"
version = "0.1.0"
description = "A ChatBOT"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "openai>=1.90.0",
    "streamlit>=1.46.0",
    "watchdog>=6.0.0",
]
